In [10]:
import numpy as np

In [32]:
myarray3 = np.array( [[11,22,33,44,55],[66,77,88,99,1 ]]  )

In [11]:
myarray = np.array([[11,22,33,44,55], [66,77,88,99,100]])

In [31]:
myarray4 = np.array([ 11,22,33,44,55] )

In [33]:
myarray_total3 = myarray3 + myarray4

In [25]:
print(myarray_total3)

[[ 22  44  66  88 110]
 [ 77  99 121 143 155]]


In [26]:
myarray_total3 = myarray3 * myarray4

In [27]:
print(myarray_total3)

[[ 121  484 1089 1936 3025]
 [ 726 1694 2904 4356 5500]]


In [12]:
myarray2 = np.array([1,2,3,4,5])

In [13]:
myarray_total = myarray + myarray2

In [14]:
print(myarray)

[[ 11  22  33  44  55]
 [ 66  77  88  99 100]]


In [15]:
print(myarray2)

[1 2 3 4 5]


In [16]:
print(myarray_total)

[[ 12  24  36  48  60]
 [ 67  79  91 103 105]]


In [17]:
myarray_total2 = myarray * myarray2

In [18]:
print(myarray_total2)

[[ 11  44  99 176 275]
 [ 66 154 264 396 500]]
