In [1]:
import numpy as np

In [2]:
a = np.array([11,22,33,44,55])

In [3]:
print(a)

[11 22 33 44 55]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [6]:
b = np.array([[11,22,33,44,55],[1,2,3,4,5]])

In [7]:
print(b)

[[11 22 33 44 55]
 [ 1  2  3  4  5]]


In [8]:
print(type(b))

<class 'numpy.ndarray'>


In [9]:
c = np.array([77,44,12,32],complex)

In [10]:
print(c)

[77.+0.j 44.+0.j 12.+0.j 32.+0.j]


In [11]:
print(c.ndim)

1


In [12]:
print(b.ndim)

2


In [13]:
print(c.itemsize)

16


In [14]:
print(b.itemsize)

8


In [15]:
print(c)

[77.+0.j 44.+0.j 12.+0.j 32.+0.j]


In [16]:
print(a)

[11 22 33 44 55]


In [17]:
print(a.dtype)

int64


In [18]:
print(a)

[11 22 33 44 55]


In [19]:
print(b)

[[11 22 33 44 55]
 [ 1  2  3  4  5]]


In [20]:
print(a.size)

5


In [21]:
print(b.size)

10


In [22]:
print(a.shape)

(5,)


In [23]:
print(b.shape)

(2, 5)


## Reshaping the array

In [25]:
myarray = np.array([[11 ,22 ,33, 44 ],[11 ,22, 33 ,55], [ 1  , 3 , 4 , 5]])

In [26]:
print(myarray)

[[11 22 33 44]
 [11 22 33 55]
 [ 1  3  4  5]]


In [27]:
print(myarray.shape)

(3, 4)


In [28]:
myarray2 = myarray.reshape(4,3)

In [29]:
print(myarray2)

[[11 22 33]
 [44 11 22]
 [33 55  1]
 [ 3  4  5]]


In [30]:
print(myarray)

[[11 22 33 44]
 [11 22 33 55]
 [ 1  3  4  5]]


In [32]:
print(myarray[0,1])

22


In [33]:
print(myarray[1,1])

22


In [34]:
print(myarray[2,1])

3


In [35]:
print(myarray[0,0])

11


Arithmetic operations for array

In [36]:
myarray3 = np.array([[11 ,22 ,33, 44 ],[11 ,22, 33 ,55], [ 1  , 3 , 4 , 5]])

In [37]:
myarray4 = np.array([[13 ,14 ,15, 16 ],[11 ,22, 33 ,55], [ 1  , 3 , 4 , 5]])

In [38]:
print(myarray3 * myarray4)

[[ 143  308  495  704]
 [ 121  484 1089 3025]
 [   1    9   16   25]]


In [39]:
print(myarray3 + myarray4)

[[ 24  36  48  60]
 [ 22  44  66 110]
 [  2   6   8  10]]


In [40]:
print( np.hstack((myarray3 , myarray4 )) )

[[11 22 33 44 13 14 15 16]
 [11 22 33 55 11 22 33 55]
 [ 1  3  4  5  1  3  4  5]]


In [41]:
print( np.vstack((myarray3 , myarray4 )) )

[[11 22 33 44]
 [11 22 33 55]
 [ 1  3  4  5]
 [13 14 15 16]
 [11 22 33 55]
 [ 1  3  4  5]]
