In [1]:
import numpy as np

In [2]:
myarray = [0.11,2.55,4.88,6.34]

In [3]:
myarray

[0.11, 2.55, 4.88, 6.34]

In [4]:
myarray2 = np.ceil(myarray)

In [5]:
myarray2

array([1., 3., 5., 7.])

In [6]:
myarray3 = [100.2,32.0095,54.18,777.34]

In [7]:
myarray3

[100.2, 32.0095, 54.18, 777.34]

In [8]:
myarray4 = np.ceil(myarray3)

In [9]:
myarray4

array([101.,  33.,  55., 778.])

In [15]:
myarray5 = [12.6,51.52,41.99999,10.88888]

In [11]:
myarray6 = np.fix(myarray5)

In [12]:
myarray6

array([ 1.,  5.,  4., 10.])

In [16]:
myarray7 = np.floor(myarray5)

In [17]:
myarray7

array([12., 51., 41., 10.])

In [18]:
myarray8 = np.rint(myarray5)

In [19]:
myarray5

[12.6, 51.52, 41.99999, 10.88888]

In [20]:
myarray8

array([13., 52., 42., 11.])

In [21]:
myarray8 = np.rint(myarray3)

In [22]:
myarray3

[100.2, 32.0095, 54.18, 777.34]

In [23]:
myarray8

array([100.,  32.,  54., 777.])

In [26]:
int_array = [12.6,51.52,41.99999,10.88888]

In [27]:
int_array2 = [12.1,51.02,41.29999,10.48888]

In [28]:
myarray_total = np.rint(int_array)

In [29]:
myarray_total2 = np.rint(int_array2)

In [30]:
int_array
myarray_total

array([13., 52., 42., 11.])

In [31]:
int_array

[12.6, 51.52, 41.99999, 10.88888]

In [32]:
myarray_total

array([13., 52., 42., 11.])

In [34]:
int_array2

[12.1, 51.02, 41.29999, 10.48888]

In [35]:
myarray_total2

array([12., 51., 41., 10.])

In [38]:
import numpy.matlib

In [40]:
myeyearray = np.matlib.eye( 4 , k = 0 , dtype = float)

In [41]:
myeyearray

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [46]:
myeyearray = np.matlib.eye( 5 , k = 0 , dtype = int)

In [47]:
myeyearray

matrix([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

In [48]:
myeyearray = np.matlib.identity( 5 , int)

In [49]:
myeyearray

matrix([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

In [50]:
myeyearray = np.matlib.identity( 4)

In [51]:
myeyearray

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])