In [1]:
import numpy as np

In [6]:
first_array = np.array([0,1,2,3,4,5,6,7,8,9,10,11,22,13,14,15,16,17,18,19,20,21,22,23])

In [7]:
first_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 22, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [4]:
first_array = np.array(np.arange(24))

In [5]:
first_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [8]:
np.transpose(first_array)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 22, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [9]:
second_array = first_array.reshape((3,8))

In [10]:
second_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 22, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [11]:
third_array = first_array.reshape((2,3,4))

In [12]:
third_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[22, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [13]:
first_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 22, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
second_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 22, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [15]:
third_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[22, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [16]:
np.transpose(second_array)

array([[ 0,  8, 16],
       [ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 22, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23]])

In [17]:
np.transpose(third_array)

array([[[ 0, 22],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [18]:
second_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 22, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [24]:
np.transpose(third_array , axes=(0,2,1))

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[22, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

In [22]:
third_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[22, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])