In [1]:
import numpy as np

In [2]:
myarray = np.array([1,2,3,4,5,6,7])

In [3]:
second_array = myarray

In [4]:
myarray

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
second_array

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
myarray is second_array

True

In [7]:
id(myarray)

4480147824

In [8]:
id(second_array)

4480147824

In [9]:
myarray == second_array

array([ True,  True,  True,  True,  True,  True,  True])

In [10]:
second_array[2] = 22

In [11]:
second_array

array([ 1,  2, 22,  4,  5,  6,  7])

In [12]:
myarray

array([ 1,  2, 22,  4,  5,  6,  7])

In [13]:
muhammed_array = np.array([ 11,  22, 33,  44,  55,  66 ])

In [14]:
muhammed_array == myarray

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [15]:
muhammed_array = myarray

In [16]:
muhammed_array == myarray

array([ True,  True,  True,  True,  True,  True,  True])

In [17]:
id(muhammed_array)

4480147824

In [18]:
id(myarray)

4480147824

In [19]:
myarray 

array([ 1,  2, 22,  4,  5,  6,  7])

In [20]:
muhammed_array = np.array([ 1,  2, 22,  4,  5,  6,  7])

In [21]:
muhammed_array == myarray

array([ True,  True,  True,  True,  True,  True,  True])

In [22]:
id(myarray)

4480147824

In [23]:
id(muhammed_array)

4480219456

In [24]:
id(second_array)

4480147824

In [25]:
muhammed_array is myarray

False

In [26]:
myarray

array([ 1,  2, 22,  4,  5,  6,  7])

In [27]:
muhammed_array

array([ 1,  2, 22,  4,  5,  6,  7])

In [28]:
muhammed_array[2] = 33

In [29]:
muhammed_array

array([ 1,  2, 33,  4,  5,  6,  7])

In [30]:
myarray

array([ 1,  2, 22,  4,  5,  6,  7])