In [1]:
import numpy as np

In [2]:
np.zeros((3,2),dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [3]:
myarray = np.zeros((3,2),dtype=int)

In [4]:
print(myarray)

[[0 0]
 [0 0]
 [0 0]]


In [5]:
myarray2 =  np.ones((4,3),dtype=int)

In [6]:
print(myarray2)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [7]:
myarray3 =  np.empty((2,3),dtype=int)

In [8]:
print(myarray3)

[[-8070450532247928832 -8070450532247928832                    7]
 [                   0                    0                    0]]
